name: Build docker_logs_forwarder images

on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: ghcr.io

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_docker_logs_forwarder:
    name: Build docker_logs_forwarder addon
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64 ]
        # armhf, armv7, aarch64,, i386]

    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Login to Packages Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build docker_logs_forwarder image
      uses: home-assistant/builder@master
      if: github.event.pull_request.head.repo.full_name != github.repository
      with:
        args: |
          --test \
          --${{ matrix.arch }} \
          --docker-hub $REGISTRY \
          --image ${{ github.repository}}-docker_logs_forwarder-{arch} \
          --version $GITHUB_REF_SLUG \
          --no-latest \
          --target .

    - name: Build and push docker_logs_forwarder image
      uses: home-assistant/builder@master
      if: github.event.pull_request.head.repo.full_name == github.repository
      with:
        args: |
          --${{ matrix.arch }} \
          --docker-hub $REGISTRY \
          --image ${{ github.repository}}-docker_logs_forwarder-{arch} \
          --version $GITHUB_REF_SLUG \
          --no-latest \
          --target .
